input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["pg_cdc.public.knowledge_document"]
    codec => "json"
    auto_offset_reset => "earliest"
    # 換一個新的 group_id，強迫 Logstash 從頭讀取那兩筆舊資料！
    group_id => "logstash_knowledge_sync_v2" 
  }
}

filter {
  # 1. 忽略非 CDC 標準格式的資料 (確保有 op 操作碼欄位)
  if ![op] {
    drop { }
  }

  # 2. 判斷資料庫操作類型：c (新增), u (更新), d (刪除), r (快照)
  if [op] == "d" {
    mutate {
      add_field => { "[@metadata][es_action]" => "delete" }
      add_field => { "[@metadata][doc_id]" => "%{[before][id]}" }
    }
  } else {
    mutate {
      add_field => { "[@metadata][es_action]" => "index" }
      add_field => { "[@metadata][doc_id]" => "%{[after][id]}" }
    }
    
    #  把 after 裡面的真實資料攤平抽到最外層
    ruby {
      code => "
        after_data = event.get('after')
        if after_data
          after_data.each { |k, v| event.set(k, v) }
        end
      "
    }
  }

  # 3. 清理不需要的 CDC 系統欄位，保持 ES 資料乾淨
  mutate {
    remove_field => ["before", "after", "source", "op", "ts_ms", "transaction", "@version", "@timestamp", "message", "event"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "knowledge_vector"
    action => "%{[@metadata][es_action]}"
    document_id => "%{[@metadata][doc_id]}"
  }
  
  stdout {
    codec => rubydebug
  }
}