spring.application.name=knowlege-management-module
server.port=8080

## ----------------------------------------------------
## Command 端：PostgreSQL (Source of Truth)
## ----------------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/kb_master
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA & Hibernate 設定
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

## ----------------------------------------------------
## Query 端：Elasticsearch 客製化設定
## ----------------------------------------------------
spring.elasticsearch.uris=http://localhost:19200
# 開啟 Elasticsearch 底層連線的 TRACE 日誌 (抓包用)
logging.level.org.elasticsearch.client.RestClient=TRACE

## ----------------------------------------------------
## Event / CDC 端：Kafka 消費者設定 (稽核軌跡用)
## ----------------------------------------------------
# 1. 指定 Kafka 伺服器位址 (請確認 port 是否為 9092)
spring.kafka.bootstrap-servers=localhost:9092


# 2. 預設的 Consumer Group ID
spring.kafka.consumer.group-id=audit-log-group

# 3. 超級關鍵：指定反序列化工具！
# Debezium 傳過來的是 JSON 位元組，我們必須強制把它轉成 String 字串，交給 Jackson 解析
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# 4. 讀取策略 (earliest：如果是一個新的 Group，就從 Kafka 裡最舊的資料開始讀起)
spring.kafka.consumer.auto-offset-reset=earliest

# 稽核軌跡專用的 Topic 名稱
app.kafka.topic.audit-log=pg_cdc.public.knowledge_document

# 稽核軌跡專用的 Consumer Group ID
app.kafka.group-id.audit-log=audit-log-group

# ==========================================
# 基礎連線設定 (Elasticsearch 核心)
# ==========================================
# 指向你的 docker-compose 中的 Elasticsearch port

# Spring AI - Ollama 模型調度中心
spring.ai.ollama.base-url=http://localhost:11434

# [推論大腦] qwen2.5:7b (負責總結、回答使用者問題)
spring.ai.ollama.chat.model=qwen2.5:7b
#spring.ai.ollama.chat.options.model=qwen2.5:7b
spring.ai.ollama.chat.options.temperature=0.3
spring.ai.ollama.chat.options.max-tokens=8192

# [向量引擎] Nomic-Embed-Text (負責把文字轉成 768 維度陣列)
spring.ai.ollama.embedding.model=nomic-embed-text

# 向量資料庫檢索設定 (Elasticsearch Vector Store)
# 自動建立或使用名為 knowledge_vector 的 Index
spring.ai.vectorstore.elasticsearch.index-name=knowledge_vector
# 必須與 nomic-embed-text 的輸出維度完全一致
spring.ai.vectorstore.elasticsearch.dimensions=768
# 使用餘弦相似度來比對向量距離 (業界標準)
spring.ai.vectorstore.elasticsearch.similarity=cosine

# 語意快取專用 Index (負責攔截重複問題，降低 LLM 呼叫延遲)
spring.ai.vectorstore.elasticsearch.cache-index-name=qa_semantic_cache
